=== rodas7865/AI3-2026-2027/Sprints/XML002/26774/produto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="Product">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="ProductName" type="xsd:string"/>
        <xsd:element name="ProductType" type="xsd:string"/>
        <xsd:element name="Price" type="xsd:decimal"/>
        <xsd:element name="Class" type="xsd:string"/>
        <xsd:element name="Company" type="xsd:string"/>
        <xsd:element name="Provider" minOccurs="0" maxOccurs="3">
          <xsd:complexType mixed="true">
            <xsd:sequence>
              <xsd:element name="name" type="xsd:string"/>
              <xsd:element name="city" type="xsd:string"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="ProductID" type="xsd:int" use="required"/>
      <xsd:attribute name="Category" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== rodas7865/AI3-2026-2027/Sprints/XML002/26774/produto.xml
<?xml version="1.0" encoding="UTF-8"?>
<Product ProductID="123" Category="bicycle"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="produto.xsd">
  <ProductName>Bicicleta de 3 Rodas</ProductName>
  <ProductType>Utilitário</ProductType>
  <Price>120</Price>
  <Class>Sport</Class>
  <Company>ABC Int.</Company>
  <Provider>
    <name>João</name>
    <city>Viseu</city>
  </Provider>
</Product>
